#include "serdes_ss_log.h"

int serdes_pack_ss_log(const serdes_ss_log_t *packet, uint8_t *buffer, uint16_t max_size) {
    if (!packet || !buffer) return -1;  // Null pointer error
    // Calculate payload size (excluding id)
    uint16_t payload_size = sizeof(uint32_t) + sizeof(int16_t) * 3 + sizeof(float) + sizeof(int8_t) + sizeof(float) * 4 + sizeof(float) * 4 + sizeof(uint16_t) * 3 + sizeof(float) + sizeof(float) + sizeof(float) + sizeof(int16_t) * 2 + sizeof(int16_t) + sizeof(int16_t) + sizeof(float) + sizeof(uint16_t) + sizeof(float) + sizeof(int8_t) + sizeof(float) + sizeof(int8_t) + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(int16_t) * 3 + sizeof(float) * 3 + sizeof(float) * 3 + sizeof(int32_t) + sizeof(int32_t) + sizeof(float) + sizeof(int16_t) * 3 + sizeof(float) + sizeof(float) + sizeof(float) + sizeof(uint16_t) * 8 + sizeof(uint16_t) + sizeof(uint16_t) * 12 + sizeof(uint32_t) + sizeof(int16_t) * 3 + sizeof(float) * 3 + sizeof(float) * 3 + sizeof(int32_t) + sizeof(int32_t) + sizeof(float) + sizeof(int16_t) * 3 + sizeof(uint8_t) * 3 + sizeof(uint8_t) * 3 + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint16_t) + sizeof(uint16_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint32_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(float) + sizeof(int16_t) + sizeof(uint16_t) + sizeof(int32_t) + sizeof(float) + sizeof(float) + sizeof(uint16_t) + sizeof(int32_t) + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) + sizeof(uint32_t) + sizeof(uint16_t) * 8 + sizeof(uint8_t) * 8 + sizeof(uint8_t) * 8 + sizeof(int8_t) * 8 + sizeof(uint32_t) + sizeof(int16_t) * 13;
    uint16_t total_size = 1 + 2 + 1 + payload_size + 2 + 1;  // start + len(2) + id + payload + crc + end
    if (total_size > max_size || payload_size + 1 > 1024) return -2;  // Buffer too small
    // Set start byte, payload length, and message ID
    buffer[0] = 0x7E;  // Start byte
    buffer[1] = ((payload_size + 1) >> 8) & 0xFF;  // Length MSB
    buffer[2] = (payload_size + 1) & 0xFF;  // Length LSB
    buffer[3] = SERDES_SS_LOG_ID;  // Message ID
    // Copy payload
    uint16_t offset = 4;
    memcpy(buffer + offset, &packet->logger_time_ms, sizeof(uint32_t));
    offset += sizeof(uint32_t);
    memcpy(buffer + offset, packet->fcs_mr_eul_rpy_d, sizeof(int16_t) * 3);
    offset += sizeof(int16_t) * 3;
    memcpy(buffer + offset, &packet->fcs_mr_yawrate_d, sizeof(float));
    offset += sizeof(float);
    memcpy(buffer + offset, &packet->fcs_mr_yaw_hold, sizeof(int8_t));
    offset += sizeof(int8_t);
    memcpy(buffer + offset, packet->fcs_ca_nu_des, sizeof(float) * 4);
    offset += sizeof(float) * 4;
    memcpy(buffer + offset, packet->fcs_ca_nu_alloc, sizeof(float) * 4);
    offset += sizeof(float) * 4;
    memcpy(buffer + offset, packet->fcs_ca_cerp, sizeof(uint16_t) * 3);
    offset += sizeof(uint16_t) * 3;
    memcpy(buffer + offset, &packet->fcs_mr_h_d, sizeof(float));
    offset += sizeof(float);
    memcpy(buffer + offset, &packet->fcs_mr_hdot_d, sizeof(float));
    offset += sizeof(float);
    memcpy(buffer + offset, &packet->fcs_mr_h_hold, sizeof(float));
    offset += sizeof(float);
    memcpy(buffer + offset, packet->fcs_mr_vel_ne_d, sizeof(int16_t) * 2);
    offset += sizeof(int16_t) * 2;
    memcpy(buffer + offset, &packet->fcs_fw_roll_d, sizeof(int16_t));
    offset += sizeof(int16_t);
    memcpy(buffer + offset, &packet->fcs_fw_pitch_d, sizeof(int16_t));
    offset += sizeof(int16_t);
    memcpy(buffer + offset, &packet->fcs_fw_h_d, sizeof(float));
    offset += sizeof(float);
    memcpy(buffer + offset, &packet->fcs_fw_cas_d, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(buffer + offset, &packet->fcs_mr_pit_intg, sizeof(float));
    offset += sizeof(float);
    memcpy(buffer + offset, &packet->fcs_mr_pit_intg_sat, sizeof(int8_t));
    offset += sizeof(int8_t);
    memcpy(buffer + offset, &packet->fcs_fw_pit_intg, sizeof(float));
    offset += sizeof(float);
    memcpy(buffer + offset, &packet->fcs_fw_pit_intg_sat, sizeof(int8_t));
    offset += sizeof(int8_t);
    memcpy(buffer + offset, &packet->fcs_vom_status, sizeof(uint8_t));
    offset += sizeof(uint8_t);
    memcpy(buffer + offset, &packet->fcs_status_flags, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(buffer + offset, packet->fcs_euler_rpy, sizeof(int16_t) * 3);
    offset += sizeof(int16_t) * 3;
    memcpy(buffer + offset, packet->fcs_omg_xyz, sizeof(float) * 3);
    offset += sizeof(float) * 3;
    memcpy(buffer + offset, packet->fcs_acc_xyz, sizeof(float) * 3);
    offset += sizeof(float) * 3;
    memcpy(buffer + offset, &packet->fcs_lat, sizeof(int32_t));
    offset += sizeof(int32_t);
    memcpy(buffer + offset, &packet->fcs_lon, sizeof(int32_t));
    offset += sizeof(int32_t);
    memcpy(buffer + offset, &packet->fcs_alt_gps_amsl, sizeof(float));
    offset += sizeof(float);
    memcpy(buffer + offset, packet->fcs_vel_ned, sizeof(int16_t) * 3);
    offset += sizeof(int16_t) * 3;
    memcpy(buffer + offset, &packet->fcs_aspd_cas, sizeof(float));
    offset += sizeof(float);
    memcpy(buffer + offset, &packet->fcs_alt_baro_amsl, sizeof(float));
    offset += sizeof(float);
    memcpy(buffer + offset, &packet->fcs_alt_radalt_filt, sizeof(float));
    offset += sizeof(float);
    memcpy(buffer + offset, packet->cmd_rotor_cval, sizeof(uint16_t) * 8);
    offset += sizeof(uint16_t) * 8;
    memcpy(buffer + offset, &packet->cmd_pusher_pwm, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(buffer + offset, packet->cmd_servo_deg, sizeof(uint16_t) * 12);
    offset += sizeof(uint16_t) * 12;
    memcpy(buffer + offset, &packet->ins1_time_ms, sizeof(uint32_t));
    offset += sizeof(uint32_t);
    memcpy(buffer + offset, packet->ins1_euler_rpy, sizeof(int16_t) * 3);
    offset += sizeof(int16_t) * 3;
    memcpy(buffer + offset, packet->ins1_omg, sizeof(float) * 3);
    offset += sizeof(float) * 3;
    memcpy(buffer + offset, packet->ins1_acc, sizeof(float) * 3);
    offset += sizeof(float) * 3;
    memcpy(buffer + offset, &packet->ins1_lat, sizeof(int32_t));
    offset += sizeof(int32_t);
    memcpy(buffer + offset, &packet->ins1_lon, sizeof(int32_t));
    offset += sizeof(int32_t);
    memcpy(buffer + offset, &packet->ins1_alt_amsl, sizeof(float));
    offset += sizeof(float);
    memcpy(buffer + offset, packet->ins1_vel_ned, sizeof(int16_t) * 3);
    offset += sizeof(int16_t) * 3;
    memcpy(buffer + offset, packet->ins1_kf_pos_cov_lla, sizeof(uint8_t) * 3);
    offset += sizeof(uint8_t) * 3;
    memcpy(buffer + offset, packet->ins1_kf_vel_cov_ned, sizeof(uint8_t) * 3);
    offset += sizeof(uint8_t) * 3;
    memcpy(buffer + offset, &packet->ins1_gnss_sat_used, sizeof(uint8_t));
    offset += sizeof(uint8_t);
    memcpy(buffer + offset, &packet->ins1_gnss_pdop, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(buffer + offset, &packet->ins1_gnss_h_acc, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(buffer + offset, &packet->ins1_gnss_v_acc, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(buffer + offset, &packet->ins1_gnss_sol_type, sizeof(uint8_t));
    offset += sizeof(uint8_t);
    memcpy(buffer + offset, &packet->ins1_gnss_info1, sizeof(uint8_t));
    offset += sizeof(uint8_t);
    memcpy(buffer + offset, &packet->ins1_gnss_info2, sizeof(uint8_t));
    offset += sizeof(uint8_t);
    memcpy(buffer + offset, &packet->ins1_ins_sol_status, sizeof(uint8_t));
    offset += sizeof(uint8_t);
    memcpy(buffer + offset, &packet->ins1_flags, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(buffer + offset, &packet->ads_time_ms, sizeof(uint32_t));
    offset += sizeof(uint32_t);
    memcpy(buffer + offset, &packet->ads_aspd_cas, sizeof(int16_t));
    offset += sizeof(int16_t);
    memcpy(buffer + offset, &packet->ads_aoa, sizeof(int16_t));
    offset += sizeof(int16_t);
    memcpy(buffer + offset, &packet->ads_aos, sizeof(int16_t));
    offset += sizeof(int16_t);
    memcpy(buffer + offset, &packet->ads_aspd_tas, sizeof(int16_t));
    offset += sizeof(int16_t);
    memcpy(buffer + offset, &packet->ads_alt_baro_amsl, sizeof(float));
    offset += sizeof(float);
    memcpy(buffer + offset, &packet->ads_oat_celsius, sizeof(int16_t));
    offset += sizeof(int16_t);
    memcpy(buffer + offset, &packet->ads_flags, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(buffer + offset, &packet->radalt_time_ms, sizeof(int32_t));
    offset += sizeof(int32_t);
    memcpy(buffer + offset, &packet->radalt_alt_raw, sizeof(float));
    offset += sizeof(float);
    memcpy(buffer + offset, &packet->radalt_snr, sizeof(float));
    offset += sizeof(float);
    memcpy(buffer + offset, &packet->radalt_flags, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(buffer + offset, &packet->pilot_time_ms, sizeof(int32_t));
    offset += sizeof(int32_t);
    memcpy(buffer + offset, packet->pilot_roll, sizeof(int16_t) * 2);
    offset += sizeof(int16_t) * 2;
    memcpy(buffer + offset, packet->pilot_pitch, sizeof(int16_t) * 2);
    offset += sizeof(int16_t) * 2;
    memcpy(buffer + offset, packet->pilot_thrust, sizeof(int16_t) * 2);
    offset += sizeof(int16_t) * 2;
    memcpy(buffer + offset, packet->pilot_yaw, sizeof(int16_t) * 2);
    offset += sizeof(int16_t) * 2;
    memcpy(buffer + offset, packet->pilot_pusher, sizeof(int16_t) * 2);
    offset += sizeof(int16_t) * 2;
    memcpy(buffer + offset, packet->pilot_arm_ch, sizeof(int16_t) * 2);
    offset += sizeof(int16_t) * 2;
    memcpy(buffer + offset, packet->pilot_sw_a, sizeof(int8_t) * 2);
    offset += sizeof(int8_t) * 2;
    memcpy(buffer + offset, packet->pilot_sw_b, sizeof(int8_t) * 2);
    offset += sizeof(int8_t) * 2;
    memcpy(buffer + offset, packet->pilot_flags, sizeof(int8_t) * 2);
    offset += sizeof(int8_t) * 2;
    memcpy(buffer + offset, &packet->pilot_rssi, sizeof(int8_t));
    offset += sizeof(int8_t);
    memcpy(buffer + offset, &packet->epu_time_ms, sizeof(uint32_t));
    offset += sizeof(uint32_t);
    memcpy(buffer + offset, packet->epu_rpm, sizeof(uint16_t) * 8);
    offset += sizeof(uint16_t) * 8;
    memcpy(buffer + offset, packet->epu_current, sizeof(uint8_t) * 8);
    offset += sizeof(uint8_t) * 8;
    memcpy(buffer + offset, packet->epu_voltage, sizeof(uint8_t) * 8);
    offset += sizeof(uint8_t) * 8;
    memcpy(buffer + offset, packet->epu_temp, sizeof(int8_t) * 8);
    offset += sizeof(int8_t) * 8;
    memcpy(buffer + offset, &packet->servo_time_ms, sizeof(uint32_t));
    offset += sizeof(uint32_t);
    memcpy(buffer + offset, packet->servo_pos_deg, sizeof(int16_t) * 13);
    offset += sizeof(int16_t) * 13;
    // Calculate and append CRC
    uint16_t crc = calculate_crc16(buffer, 4 + payload_size);
    buffer[offset] = (crc >> 8) & 0xFF;
    buffer[offset + 1] = crc & 0xFF;
    offset += 2;
    // Set end byte
    buffer[offset] = 0xAA;
    return (int)total_size;  // Return total number of bytes filled
}

int serdes_unpack_ss_log(const uint8_t *buffer, uint16_t buffer_size, serdes_ss_log_t *packet) {
    if (!buffer || !packet || buffer_size < 7) return -1;  // Minimum size: start + len(2) + id + empty payload + crc + end
    // Verify start byte
    if (buffer[0] != 0x7E) return -1;  // Invalid start byte
    // Verify payload length and buffer size
    uint16_t payload_len = (buffer[1] << 8) | buffer[2];
    uint16_t expected_payload_size = sizeof(uint32_t) + sizeof(int16_t) * 3 + sizeof(float) + sizeof(int8_t) + sizeof(float) * 4 + sizeof(float) * 4 + sizeof(uint16_t) * 3 + sizeof(float) + sizeof(float) + sizeof(float) + sizeof(int16_t) * 2 + sizeof(int16_t) + sizeof(int16_t) + sizeof(float) + sizeof(uint16_t) + sizeof(float) + sizeof(int8_t) + sizeof(float) + sizeof(int8_t) + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(int16_t) * 3 + sizeof(float) * 3 + sizeof(float) * 3 + sizeof(int32_t) + sizeof(int32_t) + sizeof(float) + sizeof(int16_t) * 3 + sizeof(float) + sizeof(float) + sizeof(float) + sizeof(uint16_t) * 8 + sizeof(uint16_t) + sizeof(uint16_t) * 12 + sizeof(uint32_t) + sizeof(int16_t) * 3 + sizeof(float) * 3 + sizeof(float) * 3 + sizeof(int32_t) + sizeof(int32_t) + sizeof(float) + sizeof(int16_t) * 3 + sizeof(uint8_t) * 3 + sizeof(uint8_t) * 3 + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint16_t) + sizeof(uint16_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint32_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(float) + sizeof(int16_t) + sizeof(uint16_t) + sizeof(int32_t) + sizeof(float) + sizeof(float) + sizeof(uint16_t) + sizeof(int32_t) + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) + sizeof(uint32_t) + sizeof(uint16_t) * 8 + sizeof(uint8_t) * 8 + sizeof(uint8_t) * 8 + sizeof(int8_t) * 8 + sizeof(uint32_t) + sizeof(int16_t) * 13 + 1;  // Payload + id
    uint16_t expected_total_size = 1 + 2 + 1 + sizeof(uint32_t) + sizeof(int16_t) * 3 + sizeof(float) + sizeof(int8_t) + sizeof(float) * 4 + sizeof(float) * 4 + sizeof(uint16_t) * 3 + sizeof(float) + sizeof(float) + sizeof(float) + sizeof(int16_t) * 2 + sizeof(int16_t) + sizeof(int16_t) + sizeof(float) + sizeof(uint16_t) + sizeof(float) + sizeof(int8_t) + sizeof(float) + sizeof(int8_t) + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(int16_t) * 3 + sizeof(float) * 3 + sizeof(float) * 3 + sizeof(int32_t) + sizeof(int32_t) + sizeof(float) + sizeof(int16_t) * 3 + sizeof(float) + sizeof(float) + sizeof(float) + sizeof(uint16_t) * 8 + sizeof(uint16_t) + sizeof(uint16_t) * 12 + sizeof(uint32_t) + sizeof(int16_t) * 3 + sizeof(float) * 3 + sizeof(float) * 3 + sizeof(int32_t) + sizeof(int32_t) + sizeof(float) + sizeof(int16_t) * 3 + sizeof(uint8_t) * 3 + sizeof(uint8_t) * 3 + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint16_t) + sizeof(uint16_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint32_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(float) + sizeof(int16_t) + sizeof(uint16_t) + sizeof(int32_t) + sizeof(float) + sizeof(float) + sizeof(uint16_t) + sizeof(int32_t) + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) + sizeof(uint32_t) + sizeof(uint16_t) * 8 + sizeof(uint8_t) * 8 + sizeof(uint8_t) * 8 + sizeof(int8_t) * 8 + sizeof(uint32_t) + sizeof(int16_t) * 13 + 2 + 1;
    if (payload_len != expected_payload_size || buffer_size < expected_total_size || payload_len > 1025) return -1;  // Invalid size
    // Verify message ID
    if (buffer[3] != SERDES_SS_LOG_ID) return -1;  // Wrong message ID
    // Verify end byte
    if (buffer[4 + sizeof(uint32_t) + sizeof(int16_t) * 3 + sizeof(float) + sizeof(int8_t) + sizeof(float) * 4 + sizeof(float) * 4 + sizeof(uint16_t) * 3 + sizeof(float) + sizeof(float) + sizeof(float) + sizeof(int16_t) * 2 + sizeof(int16_t) + sizeof(int16_t) + sizeof(float) + sizeof(uint16_t) + sizeof(float) + sizeof(int8_t) + sizeof(float) + sizeof(int8_t) + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(int16_t) * 3 + sizeof(float) * 3 + sizeof(float) * 3 + sizeof(int32_t) + sizeof(int32_t) + sizeof(float) + sizeof(int16_t) * 3 + sizeof(float) + sizeof(float) + sizeof(float) + sizeof(uint16_t) * 8 + sizeof(uint16_t) + sizeof(uint16_t) * 12 + sizeof(uint32_t) + sizeof(int16_t) * 3 + sizeof(float) * 3 + sizeof(float) * 3 + sizeof(int32_t) + sizeof(int32_t) + sizeof(float) + sizeof(int16_t) * 3 + sizeof(uint8_t) * 3 + sizeof(uint8_t) * 3 + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint16_t) + sizeof(uint16_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint32_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(float) + sizeof(int16_t) + sizeof(uint16_t) + sizeof(int32_t) + sizeof(float) + sizeof(float) + sizeof(uint16_t) + sizeof(int32_t) + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) + sizeof(uint32_t) + sizeof(uint16_t) * 8 + sizeof(uint8_t) * 8 + sizeof(uint8_t) * 8 + sizeof(int8_t) * 8 + sizeof(uint32_t) + sizeof(int16_t) * 13 + 2] != 0xAA) return -1;  // Invalid end byte
    // Verify CRC
    uint16_t received_crc = (buffer[4 + sizeof(uint32_t) + sizeof(int16_t) * 3 + sizeof(float) + sizeof(int8_t) + sizeof(float) * 4 + sizeof(float) * 4 + sizeof(uint16_t) * 3 + sizeof(float) + sizeof(float) + sizeof(float) + sizeof(int16_t) * 2 + sizeof(int16_t) + sizeof(int16_t) + sizeof(float) + sizeof(uint16_t) + sizeof(float) + sizeof(int8_t) + sizeof(float) + sizeof(int8_t) + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(int16_t) * 3 + sizeof(float) * 3 + sizeof(float) * 3 + sizeof(int32_t) + sizeof(int32_t) + sizeof(float) + sizeof(int16_t) * 3 + sizeof(float) + sizeof(float) + sizeof(float) + sizeof(uint16_t) * 8 + sizeof(uint16_t) + sizeof(uint16_t) * 12 + sizeof(uint32_t) + sizeof(int16_t) * 3 + sizeof(float) * 3 + sizeof(float) * 3 + sizeof(int32_t) + sizeof(int32_t) + sizeof(float) + sizeof(int16_t) * 3 + sizeof(uint8_t) * 3 + sizeof(uint8_t) * 3 + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint16_t) + sizeof(uint16_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint32_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(float) + sizeof(int16_t) + sizeof(uint16_t) + sizeof(int32_t) + sizeof(float) + sizeof(float) + sizeof(uint16_t) + sizeof(int32_t) + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) + sizeof(uint32_t) + sizeof(uint16_t) * 8 + sizeof(uint8_t) * 8 + sizeof(uint8_t) * 8 + sizeof(int8_t) * 8 + sizeof(uint32_t) + sizeof(int16_t) * 13] << 8) | buffer[4 + sizeof(uint32_t) + sizeof(int16_t) * 3 + sizeof(float) + sizeof(int8_t) + sizeof(float) * 4 + sizeof(float) * 4 + sizeof(uint16_t) * 3 + sizeof(float) + sizeof(float) + sizeof(float) + sizeof(int16_t) * 2 + sizeof(int16_t) + sizeof(int16_t) + sizeof(float) + sizeof(uint16_t) + sizeof(float) + sizeof(int8_t) + sizeof(float) + sizeof(int8_t) + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(int16_t) * 3 + sizeof(float) * 3 + sizeof(float) * 3 + sizeof(int32_t) + sizeof(int32_t) + sizeof(float) + sizeof(int16_t) * 3 + sizeof(float) + sizeof(float) + sizeof(float) + sizeof(uint16_t) * 8 + sizeof(uint16_t) + sizeof(uint16_t) * 12 + sizeof(uint32_t) + sizeof(int16_t) * 3 + sizeof(float) * 3 + sizeof(float) * 3 + sizeof(int32_t) + sizeof(int32_t) + sizeof(float) + sizeof(int16_t) * 3 + sizeof(uint8_t) * 3 + sizeof(uint8_t) * 3 + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint16_t) + sizeof(uint16_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint32_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(float) + sizeof(int16_t) + sizeof(uint16_t) + sizeof(int32_t) + sizeof(float) + sizeof(float) + sizeof(uint16_t) + sizeof(int32_t) + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) + sizeof(uint32_t) + sizeof(uint16_t) * 8 + sizeof(uint8_t) * 8 + sizeof(uint8_t) * 8 + sizeof(int8_t) * 8 + sizeof(uint32_t) + sizeof(int16_t) * 13 + 1];
    uint16_t calculated_crc = calculate_crc16(buffer, 4 + sizeof(uint32_t) + sizeof(int16_t) * 3 + sizeof(float) + sizeof(int8_t) + sizeof(float) * 4 + sizeof(float) * 4 + sizeof(uint16_t) * 3 + sizeof(float) + sizeof(float) + sizeof(float) + sizeof(int16_t) * 2 + sizeof(int16_t) + sizeof(int16_t) + sizeof(float) + sizeof(uint16_t) + sizeof(float) + sizeof(int8_t) + sizeof(float) + sizeof(int8_t) + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(int16_t) * 3 + sizeof(float) * 3 + sizeof(float) * 3 + sizeof(int32_t) + sizeof(int32_t) + sizeof(float) + sizeof(int16_t) * 3 + sizeof(float) + sizeof(float) + sizeof(float) + sizeof(uint16_t) * 8 + sizeof(uint16_t) + sizeof(uint16_t) * 12 + sizeof(uint32_t) + sizeof(int16_t) * 3 + sizeof(float) * 3 + sizeof(float) * 3 + sizeof(int32_t) + sizeof(int32_t) + sizeof(float) + sizeof(int16_t) * 3 + sizeof(uint8_t) * 3 + sizeof(uint8_t) * 3 + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint16_t) + sizeof(uint16_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint16_t) + sizeof(uint32_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(int16_t) + sizeof(float) + sizeof(int16_t) + sizeof(uint16_t) + sizeof(int32_t) + sizeof(float) + sizeof(float) + sizeof(uint16_t) + sizeof(int32_t) + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int16_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) * 2 + sizeof(int8_t) + sizeof(uint32_t) + sizeof(uint16_t) * 8 + sizeof(uint8_t) * 8 + sizeof(uint8_t) * 8 + sizeof(int8_t) * 8 + sizeof(uint32_t) + sizeof(int16_t) * 13);
    if (received_crc != calculated_crc) return -2;  // CRC mismatch
    // Copy payload to packet
    uint16_t offset = 4;
    memcpy(&packet->logger_time_ms, buffer + offset, sizeof(uint32_t));
    offset += sizeof(uint32_t);
    memcpy(packet->fcs_mr_eul_rpy_d, buffer + offset, sizeof(int16_t) * 3);
    offset += sizeof(int16_t) * 3;
    memcpy(&packet->fcs_mr_yawrate_d, buffer + offset, sizeof(float));
    offset += sizeof(float);
    memcpy(&packet->fcs_mr_yaw_hold, buffer + offset, sizeof(int8_t));
    offset += sizeof(int8_t);
    memcpy(packet->fcs_ca_nu_des, buffer + offset, sizeof(float) * 4);
    offset += sizeof(float) * 4;
    memcpy(packet->fcs_ca_nu_alloc, buffer + offset, sizeof(float) * 4);
    offset += sizeof(float) * 4;
    memcpy(packet->fcs_ca_cerp, buffer + offset, sizeof(uint16_t) * 3);
    offset += sizeof(uint16_t) * 3;
    memcpy(&packet->fcs_mr_h_d, buffer + offset, sizeof(float));
    offset += sizeof(float);
    memcpy(&packet->fcs_mr_hdot_d, buffer + offset, sizeof(float));
    offset += sizeof(float);
    memcpy(&packet->fcs_mr_h_hold, buffer + offset, sizeof(float));
    offset += sizeof(float);
    memcpy(packet->fcs_mr_vel_ne_d, buffer + offset, sizeof(int16_t) * 2);
    offset += sizeof(int16_t) * 2;
    memcpy(&packet->fcs_fw_roll_d, buffer + offset, sizeof(int16_t));
    offset += sizeof(int16_t);
    memcpy(&packet->fcs_fw_pitch_d, buffer + offset, sizeof(int16_t));
    offset += sizeof(int16_t);
    memcpy(&packet->fcs_fw_h_d, buffer + offset, sizeof(float));
    offset += sizeof(float);
    memcpy(&packet->fcs_fw_cas_d, buffer + offset, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(&packet->fcs_mr_pit_intg, buffer + offset, sizeof(float));
    offset += sizeof(float);
    memcpy(&packet->fcs_mr_pit_intg_sat, buffer + offset, sizeof(int8_t));
    offset += sizeof(int8_t);
    memcpy(&packet->fcs_fw_pit_intg, buffer + offset, sizeof(float));
    offset += sizeof(float);
    memcpy(&packet->fcs_fw_pit_intg_sat, buffer + offset, sizeof(int8_t));
    offset += sizeof(int8_t);
    memcpy(&packet->fcs_vom_status, buffer + offset, sizeof(uint8_t));
    offset += sizeof(uint8_t);
    memcpy(&packet->fcs_status_flags, buffer + offset, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(packet->fcs_euler_rpy, buffer + offset, sizeof(int16_t) * 3);
    offset += sizeof(int16_t) * 3;
    memcpy(packet->fcs_omg_xyz, buffer + offset, sizeof(float) * 3);
    offset += sizeof(float) * 3;
    memcpy(packet->fcs_acc_xyz, buffer + offset, sizeof(float) * 3);
    offset += sizeof(float) * 3;
    memcpy(&packet->fcs_lat, buffer + offset, sizeof(int32_t));
    offset += sizeof(int32_t);
    memcpy(&packet->fcs_lon, buffer + offset, sizeof(int32_t));
    offset += sizeof(int32_t);
    memcpy(&packet->fcs_alt_gps_amsl, buffer + offset, sizeof(float));
    offset += sizeof(float);
    memcpy(packet->fcs_vel_ned, buffer + offset, sizeof(int16_t) * 3);
    offset += sizeof(int16_t) * 3;
    memcpy(&packet->fcs_aspd_cas, buffer + offset, sizeof(float));
    offset += sizeof(float);
    memcpy(&packet->fcs_alt_baro_amsl, buffer + offset, sizeof(float));
    offset += sizeof(float);
    memcpy(&packet->fcs_alt_radalt_filt, buffer + offset, sizeof(float));
    offset += sizeof(float);
    memcpy(packet->cmd_rotor_cval, buffer + offset, sizeof(uint16_t) * 8);
    offset += sizeof(uint16_t) * 8;
    memcpy(&packet->cmd_pusher_pwm, buffer + offset, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(packet->cmd_servo_deg, buffer + offset, sizeof(uint16_t) * 12);
    offset += sizeof(uint16_t) * 12;
    memcpy(&packet->ins1_time_ms, buffer + offset, sizeof(uint32_t));
    offset += sizeof(uint32_t);
    memcpy(packet->ins1_euler_rpy, buffer + offset, sizeof(int16_t) * 3);
    offset += sizeof(int16_t) * 3;
    memcpy(packet->ins1_omg, buffer + offset, sizeof(float) * 3);
    offset += sizeof(float) * 3;
    memcpy(packet->ins1_acc, buffer + offset, sizeof(float) * 3);
    offset += sizeof(float) * 3;
    memcpy(&packet->ins1_lat, buffer + offset, sizeof(int32_t));
    offset += sizeof(int32_t);
    memcpy(&packet->ins1_lon, buffer + offset, sizeof(int32_t));
    offset += sizeof(int32_t);
    memcpy(&packet->ins1_alt_amsl, buffer + offset, sizeof(float));
    offset += sizeof(float);
    memcpy(packet->ins1_vel_ned, buffer + offset, sizeof(int16_t) * 3);
    offset += sizeof(int16_t) * 3;
    memcpy(packet->ins1_kf_pos_cov_lla, buffer + offset, sizeof(uint8_t) * 3);
    offset += sizeof(uint8_t) * 3;
    memcpy(packet->ins1_kf_vel_cov_ned, buffer + offset, sizeof(uint8_t) * 3);
    offset += sizeof(uint8_t) * 3;
    memcpy(&packet->ins1_gnss_sat_used, buffer + offset, sizeof(uint8_t));
    offset += sizeof(uint8_t);
    memcpy(&packet->ins1_gnss_pdop, buffer + offset, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(&packet->ins1_gnss_h_acc, buffer + offset, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(&packet->ins1_gnss_v_acc, buffer + offset, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(&packet->ins1_gnss_sol_type, buffer + offset, sizeof(uint8_t));
    offset += sizeof(uint8_t);
    memcpy(&packet->ins1_gnss_info1, buffer + offset, sizeof(uint8_t));
    offset += sizeof(uint8_t);
    memcpy(&packet->ins1_gnss_info2, buffer + offset, sizeof(uint8_t));
    offset += sizeof(uint8_t);
    memcpy(&packet->ins1_ins_sol_status, buffer + offset, sizeof(uint8_t));
    offset += sizeof(uint8_t);
    memcpy(&packet->ins1_flags, buffer + offset, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(&packet->ads_time_ms, buffer + offset, sizeof(uint32_t));
    offset += sizeof(uint32_t);
    memcpy(&packet->ads_aspd_cas, buffer + offset, sizeof(int16_t));
    offset += sizeof(int16_t);
    memcpy(&packet->ads_aoa, buffer + offset, sizeof(int16_t));
    offset += sizeof(int16_t);
    memcpy(&packet->ads_aos, buffer + offset, sizeof(int16_t));
    offset += sizeof(int16_t);
    memcpy(&packet->ads_aspd_tas, buffer + offset, sizeof(int16_t));
    offset += sizeof(int16_t);
    memcpy(&packet->ads_alt_baro_amsl, buffer + offset, sizeof(float));
    offset += sizeof(float);
    memcpy(&packet->ads_oat_celsius, buffer + offset, sizeof(int16_t));
    offset += sizeof(int16_t);
    memcpy(&packet->ads_flags, buffer + offset, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(&packet->radalt_time_ms, buffer + offset, sizeof(int32_t));
    offset += sizeof(int32_t);
    memcpy(&packet->radalt_alt_raw, buffer + offset, sizeof(float));
    offset += sizeof(float);
    memcpy(&packet->radalt_snr, buffer + offset, sizeof(float));
    offset += sizeof(float);
    memcpy(&packet->radalt_flags, buffer + offset, sizeof(uint16_t));
    offset += sizeof(uint16_t);
    memcpy(&packet->pilot_time_ms, buffer + offset, sizeof(int32_t));
    offset += sizeof(int32_t);
    memcpy(packet->pilot_roll, buffer + offset, sizeof(int16_t) * 2);
    offset += sizeof(int16_t) * 2;
    memcpy(packet->pilot_pitch, buffer + offset, sizeof(int16_t) * 2);
    offset += sizeof(int16_t) * 2;
    memcpy(packet->pilot_thrust, buffer + offset, sizeof(int16_t) * 2);
    offset += sizeof(int16_t) * 2;
    memcpy(packet->pilot_yaw, buffer + offset, sizeof(int16_t) * 2);
    offset += sizeof(int16_t) * 2;
    memcpy(packet->pilot_pusher, buffer + offset, sizeof(int16_t) * 2);
    offset += sizeof(int16_t) * 2;
    memcpy(packet->pilot_arm_ch, buffer + offset, sizeof(int16_t) * 2);
    offset += sizeof(int16_t) * 2;
    memcpy(packet->pilot_sw_a, buffer + offset, sizeof(int8_t) * 2);
    offset += sizeof(int8_t) * 2;
    memcpy(packet->pilot_sw_b, buffer + offset, sizeof(int8_t) * 2);
    offset += sizeof(int8_t) * 2;
    memcpy(packet->pilot_flags, buffer + offset, sizeof(int8_t) * 2);
    offset += sizeof(int8_t) * 2;
    memcpy(&packet->pilot_rssi, buffer + offset, sizeof(int8_t));
    offset += sizeof(int8_t);
    memcpy(&packet->epu_time_ms, buffer + offset, sizeof(uint32_t));
    offset += sizeof(uint32_t);
    memcpy(packet->epu_rpm, buffer + offset, sizeof(uint16_t) * 8);
    offset += sizeof(uint16_t) * 8;
    memcpy(packet->epu_current, buffer + offset, sizeof(uint8_t) * 8);
    offset += sizeof(uint8_t) * 8;
    memcpy(packet->epu_voltage, buffer + offset, sizeof(uint8_t) * 8);
    offset += sizeof(uint8_t) * 8;
    memcpy(packet->epu_temp, buffer + offset, sizeof(int8_t) * 8);
    offset += sizeof(int8_t) * 8;
    memcpy(&packet->servo_time_ms, buffer + offset, sizeof(uint32_t));
    offset += sizeof(uint32_t);
    memcpy(packet->servo_pos_deg, buffer + offset, sizeof(int16_t) * 13);
    offset += sizeof(int16_t) * 13;
    return 0;
}