/******[Configuration Header]*****************************************//**
\file
\brief
  Module Title       : Buffer definition

  Abstract           : This is a template for the UART PL CSC configuration
                       of the interfaces.
                       The file should be copied to the application code
                       space, updated for the required buffers, and renamed
                       to a c file.

  Software Structure : SRS References: Document numbers and versions.
                       SDD References: Document numbers and versions.

*************************************************************************/

/***** Includes *********************************************************/

#include "soc/defines/d_common_types.h"

#include "xparameters.h"
#include "soc/uart/d_uart_pl_cfg.h"
#include "sru/platform/ioc.h"

/***** Constants ********************************************************/
const d_UART_PL_Configuration_t d_UART_PL_Configuration[] =
{
  { //2
    XPAR_UART_FDX0A_CORE16550_BASEADDR,
    XPAR_UART_FDX0A_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_UART_IRQ_INTR
  },
  { //3
    XPAR_UART_FDX0B_CORE16550_BASEADDR,
    XPAR_UART_FDX0B_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_UART_IRQ_INTR
  },
  { //4
    XPAR_UART_HDX0_CORE16550_BASEADDR,
    XPAR_UART_HDX0_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_UART_IRQ_INTR
  },
  { //5
    XPAR_UART_HDX1_CORE16550_BASEADDR,
    XPAR_UART_HDX1_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_UART_IRQ_INTR
  },
  { //6
    XPAR_GNSS_GNSS_1_CORE16550_BASEADDR,
    XPAR_GNSS_GNSS_1_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_UART_IRQ_INTR
  },
  { //7
    XPAR_GNSS_GNSS_2_CORE16550_BASEADDR,
    XPAR_GNSS_GNSS_2_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_UART_IRQ_INTR
  },
  { //8
    XPAR_IMU_IMU_CORE16550_BASEADDR, 
    XPAR_IMU_IMU_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_UART_IRQ_INTR
  },
  { //9
    XPAR_UART_FTDI_CORE16550_BASEADDR,
    XPAR_UART_FTDI_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_UART_IRQ_INTR
  },
  { //10
    XPAR_IOCA_AXIOE_BASEADDR + IOC_FDX_0_A_CORE16550_BASEADDR,
    IOC_FDX_0_A_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC0_IRQ_INTR
  },
  { //11
    XPAR_IOCA_AXIOE_BASEADDR + IOC_FDX_0_B_CORE16550_BASEADDR,
    IOC_FDX_0_B_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC0_IRQ_INTR
  },
  { //12
    XPAR_IOCA_AXIOE_BASEADDR + IOC_FDX_1_A_CORE16550_BASEADDR,
    IOC_FDX_1_A_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC0_IRQ_INTR
  },
  { //13
    XPAR_IOCA_AXIOE_BASEADDR + IOC_FDX_1_B_CORE16550_BASEADDR,
    IOC_FDX_1_B_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC0_IRQ_INTR
  },
  { //14
    XPAR_IOCA_AXIOE_BASEADDR + IOC_FDX_2_A_CORE16550_BASEADDR,
    IOC_FDX_2_A_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC0_IRQ_INTR
  },
  { //15
    XPAR_IOCA_AXIOE_BASEADDR + IOC_FDX_2_B_CORE16550_BASEADDR,
    IOC_FDX_2_B_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC0_IRQ_INTR
  },
  { //16
    XPAR_IOCA_AXIOE_BASEADDR + IOC_FDX_3_A_CORE16550_BASEADDR,
    IOC_FDX_3_A_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC0_IRQ_INTR
  },
  { //17
    XPAR_IOCA_AXIOE_BASEADDR + IOC_FDX_3_B_CORE16550_BASEADDR,
    IOC_FDX_3_B_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC0_IRQ_INTR
  },
  { //18
    XPAR_IOCA_AXIOE_BASEADDR + IOC_FDX_4_A_CORE16550_BASEADDR,
    IOC_FDX_4_A_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC0_IRQ_INTR
  },
  { //19
    XPAR_IOCA_AXIOE_BASEADDR + IOC_FDX_4_B_CORE16550_BASEADDR,
    IOC_FDX_4_B_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC0_IRQ_INTR
  },
  { //20
    XPAR_IOCA_AXIOE_BASEADDR + IOC_HDX_0_CORE16550_BASEADDR,
    IOC_HDX_0_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC0_IRQ_INTR
  },
  { //21
    XPAR_IOCA_AXIOE_BASEADDR + IOC_HDX_1_CORE16550_BASEADDR,
    IOC_HDX_1_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC0_IRQ_INTR
  },
  { //22
    XPAR_IOCB_AXIOE_BASEADDR + IOC_FDX_0_A_CORE16550_BASEADDR,
    IOC_FDX_0_A_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC1_IRQ_INTR
  },
  { //23
    XPAR_IOCB_AXIOE_BASEADDR + IOC_FDX_0_B_CORE16550_BASEADDR,
    IOC_FDX_0_B_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC1_IRQ_INTR
  },
  { //24
    XPAR_IOCB_AXIOE_BASEADDR + IOC_FDX_1_A_CORE16550_BASEADDR,
    IOC_FDX_1_A_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC1_IRQ_INTR
  },
  { //25
    XPAR_IOCB_AXIOE_BASEADDR + IOC_FDX_1_B_CORE16550_BASEADDR,
    IOC_FDX_1_B_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC1_IRQ_INTR
  },
  { //26
    XPAR_IOCB_AXIOE_BASEADDR + IOC_FDX_2_A_CORE16550_BASEADDR,
    IOC_FDX_2_A_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC1_IRQ_INTR
  },
  { //27
    XPAR_IOCB_AXIOE_BASEADDR + IOC_FDX_2_B_CORE16550_BASEADDR,
    IOC_FDX_2_B_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC1_IRQ_INTR
  },
  { //28
    XPAR_IOCB_AXIOE_BASEADDR + IOC_FDX_3_A_CORE16550_BASEADDR,
    IOC_FDX_3_A_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC1_IRQ_INTR
  },
  { //29
    XPAR_IOCB_AXIOE_BASEADDR + IOC_FDX_3_B_CORE16550_BASEADDR,
    IOC_FDX_3_B_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC1_IRQ_INTR
  },
  { //30
    XPAR_IOCB_AXIOE_BASEADDR + IOC_FDX_4_A_CORE16550_BASEADDR,
    IOC_FDX_4_A_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC1_IRQ_INTR
  },
  { //31
    XPAR_IOCB_AXIOE_BASEADDR + IOC_FDX_4_B_CORE16550_BASEADDR,
    IOC_FDX_4_B_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC1_IRQ_INTR
  },
  { //32
    XPAR_IOCB_AXIOE_BASEADDR + IOC_HDX_0_CORE16550_BASEADDR,
    IOC_HDX_0_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC1_IRQ_INTR
  },
  { //33
    XPAR_IOCB_AXIOE_BASEADDR + IOC_HDX_1_CORE16550_BASEADDR,
    IOC_HDX_1_CORE16550_CLOCK_FREQ_HZ,
    XPAR_FABRIC_INTERRUPT_CONTROLLER_0_IOC1_IRQ_INTR
  },

};

/* Define the number of PL based UARTs */
d_UART_PL_COUNT;


/***** Type Definitions *************************************************/

/***** Variables ********************************************************/

/***** Function Declarations ********************************************/

/***** Function Definitions *********************************************/

